### ISSUE TITLE
-oi = "0" breaks/aborts for single-db  (Master checks)

### ISSUE THREAD

**Issue by jia235w5** [chriselswede/hanacleaner#18]
Created a script running "python hanacleaner.py -k <key> -dr 90 -po 0", previous version of hanacleaner.py works on HDB with active HSR and HDB w/o HSR active (Single-DB).

This current version terminates with error below due to master checks... oi = 0 should work as long as DB is identified as online. 

hanacleaner-new.py -k <KEY>-dr 90 -oi 0
Cleanup Statements will be executed (-es is default true)
Before using HANACleaner read the disclaimer!
python hanacleaner.py --disclaimer
***********************************************************
Online Check      , 2021-08-19 16:38:18    ,     -            , True         , True       , # index services: 1, # running services: 9 out of 9
Primary Check     , 2021-08-19 16:38:20    ,     -            , True         , True       ,
Traceback (most recent call last):
  File "/hanacleaner/hanacleaner-new.py", line 2133, in <module>
    main()
  File "/hanacleaner/hanacleaner-new.py", line 1949, in main
    while not online_and_master_tests(online_test_interval, local_dbinstance, local_host, logman):  #will check if Online and if Primary and not Stand-By, and then if Master, but only if online_test_interval > -1
  File "/hanacleaner/hanacleaner-new.py", line 384, in online_and_master_tests
    return is_master(local_dbinstance, local_host, logman)  #HANACleaner should only run on the Master Node
  File "/hanacleaner/hanacleaner-new.py", line 394, in is_master
    log("ERROR: Something went wrong. It found more than one (or none) host line: ", host_line)
  File "/hanacleaner/hanacleaner-new.py", line 325, in log
    if logmanager.print_to_std:
AttributeError: 'list' object has no attribute 'print_to_std'

**Comment by chriselswede** [comment]
Hi, sorry, I think this was a bug dealing with the error message wrongly. Please check if latest version solves your issue. Cheers /Chris
