### ISSUE TITLE
ERROR: Unexpted number output columns from df -h

### ISSUE THREAD

**Issue by codebeta** [chriselswede/hanacleaner#3]
When running the Python script with the command below

```ShellSession
python hanacleaner.py -k HANACLEANER1KEY -tc 30 -te 30 -td tru
```

I'm getting the following error

```ShellSession
Will now check most used memory in the file systems. If it hangs there is an issue with  df -h, then see if the -fs flag
 helps.
The most used filesystem is using 
Traceback (most recent call last):
  File "hanacleaner.py", line 1619, in <module>
    main()
  File "hanacleaner.py", line 1255, in main
    if max_filesystem_usage_in_percent(file_system, ignore_filesystems, logman) > 98:
  File "hanacleaner.py", line 560, in max_filesystem_usage_in_percent
    log("ERROR, Unexpted number output columns from df -h: \n", words)
  File "hanacleaner.py", line 250, in log
    if logmanager.print_to_std:
AttributeError: 'list' object has no attribute 'print_to_std'
```

This is on _Red Hat Enterprise Linux Server release 6.7 (Santiago)_.

The error is caused by the output of `df` displaying entries in multiple lines instead of one per line. For example

```ShellSession
Filesystem            Size  Used Avail Use% Mounted on
/dev/sda3              49G   13G   34G  28% /
mpfs                  127G  8.0K  127G   1% /dev/shm
/dev/sda1             190M   69M  111M  39% /boot
/dev/mapper/vghanadata-lv_hana_data
                      768G  677G   91G  89% /sapmnt/data
/dev/mapper/vghanadata-lv_hana_shared
                      256G  159G   98G  62% /sapmnt/shared
/dev/mapper/vghanadata-lv_usr_sap
                       50G  4.8G   46G  10% /usr/sap
/dev/sdd1             258G  104G  155G  41% /sapmnt/log
```

To resolve this, add the `-P` option to the `df` command to output the information in POSIX format, meaning the output will instead look like

```ShellSession
Filesystem                             Size  Used Avail Use% Mounted on
/dev/sda3                               49G   13G   34G  28% /
mpfs                                   127G  8.0K  127G   1% /dev/shm
/dev/sda1                              190M   69M  111M  39% /boot
/dev/mapper/vghanadata-lv_hana_data    768G  677G   91G  89% /sapmnt/data
/dev/mapper/vghanadata-lv_hana_shared  256G  159G   98G  62% /sapmnt/shared
/dev/mapper/vghanadata-lv_usr_sap       50G  4.8G   46G  10% /usr/sap
/dev/sdd1                              258G  104G  155G  41% /sapmnt/log
```

**Comment by chriselswede** [comment]
Thanks! Uploaded the change now.
