### ISSUE TITLE
HANA CLEANER issue with -pe option

### ISSUE THREAD

**Issue by Chattoraj** [chriselswede/hanacleaner#35]
Hi,

I was trying to run hana cleaner with python script. I put an option to clear pending emails (pe) with value as 10. After the script run its gives error as below:

Traceback (most recent call last):
  File "/hana/backup/Scripts/zsk-hanacleaner.py", line 2258, in <module>
    main()
  File "/hana/backup/Scripts/zsk-hanacleaner.py", line 2181, in main
    nCleaned = clean_pending_emails(pendingEmailsDays, sqlman, logman)
  File "/hana/backup/Scripts/zsk-hanacleaner.py", line 1074, in clean_pending_emails
    nbrEmailsBefore = int(run_command(sqlman.hdbsql_jAQaxU + " \"SELECT COUNT(*) FROM _SYS_STATISTICS.STATISTICS_EMAIL_PROCESSING\"").strip(' '))
ValueError: invalid literal for int() with base 10: ''

Please suggest to rectify the same.

Thanks 
Arijit

**Comment by mbertram** [comment]
Hello Arijit,

What does `SELECT COUNT(*) FROM _SYS_STATISTICS.STATISTICS_EMAIL_PROCESSING` return in hdbsql when you log in with the HANACleaner role?

It should return a number.

If you see an error message about insufficient privileges, please update your role to allow SELECT and DELETE operations on _SYS_STATISTICS.STATISTICS_EMAIL_PROCESSING.

**Comment by Chattoraj** [comment]
Thanks Matthias. Role update resolved the issue.
